ALG_NAME: "pqn_craftax"
TOTAL_TIMESTEPS: 1e9
TOTAL_TIMESTEPS_DECAY: 1e9 # will be used for decay functions, in case you want to test for less timesteps and keep decays same
NUM_ENVS: 1024 # parallel environments
NUM_STEPS: 1 # steps per environment in each update
EPS_START: 0.1
EPS_FINISH: 0.005
EPS_DECAY: 0.2
NUM_MINIBATCHES: 1 # minibatches per epoch
NUM_EPOCHS: 1 # minibatches per epoch
NORM_INPUT: True
NORM_TYPE: "layer_norm" # layer_norm or batch_norm
HIDDEN_SIZE: 1024
NUM_LAYERS: 4
LR: 0.0001
MAX_GRAD_NORM: 1.0
LR_LINEAR_DECAY: True
REW_SCALE: 1.
GAMMA: 0.99
Q_LAMBDA: False
LAMBDA: 0

# env specific
ENV_NAME: "Craftax-Symbolic-v1"
USE_OPTIMISTIC_RESETS: True
OPTIMISTIC_RESET_RATIO: 16
LOG_ACHIEVEMENTS: False

# evaluation
WANDB_LOG_INTERVAL: 100 # not log each interval since would be too much with this config
TEST_DURING_TRAINING: False 
TEST_INTERVAL: 0.01 # in terms of total updates
TEST_NUM_ENVS: 512
TEST_NUM_STEPS: 10000
EPS_TEST: 0.00 # 0 for greedy policy
