ALG_NAME: "pqn"
TOTAL_TIMESTEPS: 1e7
TOTAL_TIMESTEPS_DECAY: 1e7 # will be used for decay functions (epsilon and lr)
NUM_ENVS: 128 # parallel environments
NUM_STEPS: 32 # steps per environment in each update
EPS_START: 1.
EPS_FINISH: 0.001
EPS_DECAY: 0.1 # ratio of total updates
NUM_EPOCHS: 2 # number of epochs per update
NUM_MINIBATCHES: 32 # minibatches per epoch
NORM_TYPE: "layer_norm" # layer_norm or batch_norm
LR: 0.00025
MAX_GRAD_NORM: 10
LR_LINEAR_DECAY: False
GAMMA: 0.99
LAMBDA: 0.65

# env specific, see https://envpool.readthedocs.io/en/latest/env/atari.html
ENV_NAME: "Pong-v5"
ENV_KWARGS: 
  episodic_life: True # lost life -> done, increases sample efficiency, may hurt in some games
  reward_clip: True # reward into -1, 1
  repeat_action_probability: 0. # sticky actions
  frame_skip: 4
  noop_max: 30

# evaluation
TEST_DURING_TRAINING: True 
TEST_ENVS: 8
EPS_TEST: 0. # 0 for greedy test policy
